### ISSUE TITLE
Could not find class

### ISSUE THREAD

**Issue by zhangjianGorilla** [Estelle925/spring-plugin-load#2]
PluginApplicationContext pluginApplicationContext = new PluginApplicationContext();
            pluginApplicationContext.setParent(applicationContext);
            pluginApplicationContext.setClassLoader(pluginClassLoader);
            pluginApplicationContext.scan(Sets.newHashSet(pluginConfig.getClass().getPackage().getName()).toArray(new String[0]));
            pluginApplicationContext.refresh();
refresh()方法报错：java.lang.IllegalArgumentException: Could not find class [com.plugin.SpringPluginDemoApplication]

**Comment by zhangjianGorilla** [comment]
两个分支的pom文件没隔离，base-nacos分支的会影响master的

**Comment by ch4nhm** [comment]
base-nacos需要工程中已经集成了nacos。master就单独实现类的动态加载和springbean动态创建
